project_id = "fyxfbbkgginrbphtrhdi"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://fyxfbbkgginrbphtrhdi.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions]
verify_jwt = true

[functions.process-payment]
verify_jwt = false

[functions.manage-membership]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false

[functions.send-whale-alert]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false